# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_remove_show_premiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
