# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_delete_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('show_id', models.IntegerField()),
            ],
        ),
    ]
