# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_show_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesterdayID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.IntegerField()),
            ],
        ),
    ]
