# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_yesterdayid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
