# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0009_auto_20170621_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
